/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Sep  3 03:07:43 2013
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_UART_H__
#define BCHP_UART_H__

/***************************************************************************
 *UART - RG UART
 ***************************************************************************/
#define BCHP_UART_RBR                            0x03802800 /* Receive Buffer Register */
#define BCHP_UART_THR                            0x03802800 /* Transmit Holding Register */
#define BCHP_UART_DLH                            0x03802804 /* Divisor Latch High */
#define BCHP_UART_DLL                            0x03802800 /* Divisor Latch Low */
#define BCHP_UART_IER                            0x03802804 /* Interrupt Enable Register */
#define BCHP_UART_IIR                            0x03802808 /* Interrupt Identity Register */
#define BCHP_UART_FCR                            0x03802808 /* FIFO Control Register */
#define BCHP_UART_LCR                            0x0380280c /* Line Control Register */
#define BCHP_UART_MCR                            0x03802810 /* Modem Control Register */
#define BCHP_UART_LSR                            0x03802814 /* Line Status Register */
#define BCHP_UART_MSR                            0x03802818 /* Modem Status Register */
#define BCHP_UART_SCR                            0x0380281c /* Scratchpad Register */

/***************************************************************************
 *RBR - Receive Buffer Register
 ***************************************************************************/
/* UART :: RBR :: reserved0 [31:08] */
#define BCHP_UART_RBR_reserved0_MASK                               0xffffff00
#define BCHP_UART_RBR_reserved0_SHIFT                              8

/* UART :: RBR :: RBR [07:00] */
#define BCHP_UART_RBR_RBR_MASK                                     0x000000ff
#define BCHP_UART_RBR_RBR_SHIFT                                    0
#define BCHP_UART_RBR_RBR_DEFAULT                                  0x00000000

/***************************************************************************
 *THR - Transmit Holding Register
 ***************************************************************************/
/* UART :: THR :: reserved0 [31:08] */
#define BCHP_UART_THR_reserved0_MASK                               0xffffff00
#define BCHP_UART_THR_reserved0_SHIFT                              8

/* UART :: THR :: THR [07:00] */
#define BCHP_UART_THR_THR_MASK                                     0x000000ff
#define BCHP_UART_THR_THR_SHIFT                                    0
#define BCHP_UART_THR_THR_DEFAULT                                  0x00000000

/***************************************************************************
 *DLH - Divisor Latch High
 ***************************************************************************/
/* UART :: DLH :: reserved0 [31:08] */
#define BCHP_UART_DLH_reserved0_MASK                               0xffffff00
#define BCHP_UART_DLH_reserved0_SHIFT                              8

/* UART :: DLH :: DLH [07:00] */
#define BCHP_UART_DLH_DLH_MASK                                     0x000000ff
#define BCHP_UART_DLH_DLH_SHIFT                                    0
#define BCHP_UART_DLH_DLH_DEFAULT                                  0x00000000

/***************************************************************************
 *DLL - Divisor Latch Low
 ***************************************************************************/
/* UART :: DLL :: reserved0 [31:08] */
#define BCHP_UART_DLL_reserved0_MASK                               0xffffff00
#define BCHP_UART_DLL_reserved0_SHIFT                              8

/* UART :: DLL :: DLL [07:00] */
#define BCHP_UART_DLL_DLL_MASK                                     0x000000ff
#define BCHP_UART_DLL_DLL_SHIFT                                    0
#define BCHP_UART_DLL_DLL_DEFAULT                                  0x00000000

/***************************************************************************
 *IER - Interrupt Enable Register
 ***************************************************************************/
/* UART :: IER :: reserved0 [31:08] */
#define BCHP_UART_IER_reserved0_MASK                               0xffffff00
#define BCHP_UART_IER_reserved0_SHIFT                              8

/* UART :: IER :: PTIME [07:07] */
#define BCHP_UART_IER_PTIME_MASK                                   0x00000080
#define BCHP_UART_IER_PTIME_SHIFT                                  7
#define BCHP_UART_IER_PTIME_DEFAULT                                0x00000000

/* UART :: IER :: reserved1 [06:04] */
#define BCHP_UART_IER_reserved1_MASK                               0x00000070
#define BCHP_UART_IER_reserved1_SHIFT                              4

/* UART :: IER :: EDSSI [03:03] */
#define BCHP_UART_IER_EDSSI_MASK                                   0x00000008
#define BCHP_UART_IER_EDSSI_SHIFT                                  3
#define BCHP_UART_IER_EDSSI_DEFAULT                                0x00000000

/* UART :: IER :: ELSI [02:02] */
#define BCHP_UART_IER_ELSI_MASK                                    0x00000004
#define BCHP_UART_IER_ELSI_SHIFT                                   2
#define BCHP_UART_IER_ELSI_DEFAULT                                 0x00000000

/* UART :: IER :: ETBEI [01:01] */
#define BCHP_UART_IER_ETBEI_MASK                                   0x00000002
#define BCHP_UART_IER_ETBEI_SHIFT                                  1
#define BCHP_UART_IER_ETBEI_DEFAULT                                0x00000000

/* UART :: IER :: ERBFI [00:00] */
#define BCHP_UART_IER_ERBFI_MASK                                   0x00000001
#define BCHP_UART_IER_ERBFI_SHIFT                                  0
#define BCHP_UART_IER_ERBFI_DEFAULT                                0x00000000

/***************************************************************************
 *IIR - Interrupt Identity Register
 ***************************************************************************/
/* UART :: IIR :: reserved0 [31:08] */
#define BCHP_UART_IIR_reserved0_MASK                               0xffffff00
#define BCHP_UART_IIR_reserved0_SHIFT                              8

/* UART :: IIR :: FIFOSE [07:06] */
#define BCHP_UART_IIR_FIFOSE_MASK                                  0x000000c0
#define BCHP_UART_IIR_FIFOSE_SHIFT                                 6
#define BCHP_UART_IIR_FIFOSE_DEFAULT                               0x00000000

/* UART :: IIR :: reserved1 [05:04] */
#define BCHP_UART_IIR_reserved1_MASK                               0x00000030
#define BCHP_UART_IIR_reserved1_SHIFT                              4

/* UART :: IIR :: IID [03:00] */
#define BCHP_UART_IIR_IID_MASK                                     0x0000000f
#define BCHP_UART_IIR_IID_SHIFT                                    0
#define BCHP_UART_IIR_IID_DEFAULT                                  0x00000001

/***************************************************************************
 *FCR - FIFO Control Register
 ***************************************************************************/
/* UART :: FCR :: reserved0 [31:08] */
#define BCHP_UART_FCR_reserved0_MASK                               0xffffff00
#define BCHP_UART_FCR_reserved0_SHIFT                              8

/* UART :: FCR :: RT [07:06] */
#define BCHP_UART_FCR_RT_MASK                                      0x000000c0
#define BCHP_UART_FCR_RT_SHIFT                                     6
#define BCHP_UART_FCR_RT_DEFAULT                                   0x00000000

/* UART :: FCR :: TET [05:04] */
#define BCHP_UART_FCR_TET_MASK                                     0x00000030
#define BCHP_UART_FCR_TET_SHIFT                                    4
#define BCHP_UART_FCR_TET_DEFAULT                                  0x00000000

/* UART :: FCR :: DMAM [03:03] */
#define BCHP_UART_FCR_DMAM_MASK                                    0x00000008
#define BCHP_UART_FCR_DMAM_SHIFT                                   3
#define BCHP_UART_FCR_DMAM_DEFAULT                                 0x00000000

/* UART :: FCR :: XFIFOR [02:02] */
#define BCHP_UART_FCR_XFIFOR_MASK                                  0x00000004
#define BCHP_UART_FCR_XFIFOR_SHIFT                                 2
#define BCHP_UART_FCR_XFIFOR_DEFAULT                               0x00000000

/* UART :: FCR :: RFIFOR [01:01] */
#define BCHP_UART_FCR_RFIFOR_MASK                                  0x00000002
#define BCHP_UART_FCR_RFIFOR_SHIFT                                 1
#define BCHP_UART_FCR_RFIFOR_DEFAULT                               0x00000000

/* UART :: FCR :: FIFOE [00:00] */
#define BCHP_UART_FCR_FIFOE_MASK                                   0x00000001
#define BCHP_UART_FCR_FIFOE_SHIFT                                  0
#define BCHP_UART_FCR_FIFOE_DEFAULT                                0x00000000

/***************************************************************************
 *LCR - Line Control Register
 ***************************************************************************/
/* UART :: LCR :: reserved0 [31:08] */
#define BCHP_UART_LCR_reserved0_MASK                               0xffffff00
#define BCHP_UART_LCR_reserved0_SHIFT                              8

/* UART :: LCR :: DLAB [07:07] */
#define BCHP_UART_LCR_DLAB_MASK                                    0x00000080
#define BCHP_UART_LCR_DLAB_SHIFT                                   7
#define BCHP_UART_LCR_DLAB_DEFAULT                                 0x00000000

/* UART :: LCR :: BC [06:06] */
#define BCHP_UART_LCR_BC_MASK                                      0x00000040
#define BCHP_UART_LCR_BC_SHIFT                                     6
#define BCHP_UART_LCR_BC_DEFAULT                                   0x00000000

/* UART :: LCR :: reserved1 [05:05] */
#define BCHP_UART_LCR_reserved1_MASK                               0x00000020
#define BCHP_UART_LCR_reserved1_SHIFT                              5

/* UART :: LCR :: EPS [04:04] */
#define BCHP_UART_LCR_EPS_MASK                                     0x00000010
#define BCHP_UART_LCR_EPS_SHIFT                                    4
#define BCHP_UART_LCR_EPS_DEFAULT                                  0x00000000

/* UART :: LCR :: PEN [03:03] */
#define BCHP_UART_LCR_PEN_MASK                                     0x00000008
#define BCHP_UART_LCR_PEN_SHIFT                                    3
#define BCHP_UART_LCR_PEN_DEFAULT                                  0x00000000

/* UART :: LCR :: STOP [02:02] */
#define BCHP_UART_LCR_STOP_MASK                                    0x00000004
#define BCHP_UART_LCR_STOP_SHIFT                                   2
#define BCHP_UART_LCR_STOP_DEFAULT                                 0x00000000

/* UART :: LCR :: DLS [01:00] */
#define BCHP_UART_LCR_DLS_MASK                                     0x00000003
#define BCHP_UART_LCR_DLS_SHIFT                                    0
#define BCHP_UART_LCR_DLS_DEFAULT                                  0x00000000

/***************************************************************************
 *MCR - Modem Control Register
 ***************************************************************************/
/* UART :: MCR :: reserved0 [31:07] */
#define BCHP_UART_MCR_reserved0_MASK                               0xffffff80
#define BCHP_UART_MCR_reserved0_SHIFT                              7

/* UART :: MCR :: SIRE [06:06] */
#define BCHP_UART_MCR_SIRE_MASK                                    0x00000040
#define BCHP_UART_MCR_SIRE_SHIFT                                   6
#define BCHP_UART_MCR_SIRE_DEFAULT                                 0x00000000

/* UART :: MCR :: AFCE [05:05] */
#define BCHP_UART_MCR_AFCE_MASK                                    0x00000020
#define BCHP_UART_MCR_AFCE_SHIFT                                   5
#define BCHP_UART_MCR_AFCE_DEFAULT                                 0x00000000

/* UART :: MCR :: LB [04:04] */
#define BCHP_UART_MCR_LB_MASK                                      0x00000010
#define BCHP_UART_MCR_LB_SHIFT                                     4
#define BCHP_UART_MCR_LB_DEFAULT                                   0x00000000

/* UART :: MCR :: OUT2 [03:03] */
#define BCHP_UART_MCR_OUT2_MASK                                    0x00000008
#define BCHP_UART_MCR_OUT2_SHIFT                                   3
#define BCHP_UART_MCR_OUT2_DEFAULT                                 0x00000000

/* UART :: MCR :: OUT1 [02:02] */
#define BCHP_UART_MCR_OUT1_MASK                                    0x00000004
#define BCHP_UART_MCR_OUT1_SHIFT                                   2
#define BCHP_UART_MCR_OUT1_DEFAULT                                 0x00000000

/* UART :: MCR :: RTS [01:01] */
#define BCHP_UART_MCR_RTS_MASK                                     0x00000002
#define BCHP_UART_MCR_RTS_SHIFT                                    1
#define BCHP_UART_MCR_RTS_DEFAULT                                  0x00000000

/* UART :: MCR :: DTR [00:00] */
#define BCHP_UART_MCR_DTR_MASK                                     0x00000001
#define BCHP_UART_MCR_DTR_SHIFT                                    0
#define BCHP_UART_MCR_DTR_DEFAULT                                  0x00000000

/***************************************************************************
 *LSR - Line Status Register
 ***************************************************************************/
/* UART :: LSR :: reserved0 [31:08] */
#define BCHP_UART_LSR_reserved0_MASK                               0xffffff00
#define BCHP_UART_LSR_reserved0_SHIFT                              8

/* UART :: LSR :: RFE [07:07] */
#define BCHP_UART_LSR_RFE_MASK                                     0x00000080
#define BCHP_UART_LSR_RFE_SHIFT                                    7
#define BCHP_UART_LSR_RFE_DEFAULT                                  0x00000000

/* UART :: LSR :: TEMT [06:06] */
#define BCHP_UART_LSR_TEMT_MASK                                    0x00000040
#define BCHP_UART_LSR_TEMT_SHIFT                                   6
#define BCHP_UART_LSR_TEMT_DEFAULT                                 0x00000001

/* UART :: LSR :: THRE [05:05] */
#define BCHP_UART_LSR_THRE_MASK                                    0x00000020
#define BCHP_UART_LSR_THRE_SHIFT                                   5
#define BCHP_UART_LSR_THRE_DEFAULT                                 0x00000001

/* UART :: LSR :: BI [04:04] */
#define BCHP_UART_LSR_BI_MASK                                      0x00000010
#define BCHP_UART_LSR_BI_SHIFT                                     4
#define BCHP_UART_LSR_BI_DEFAULT                                   0x00000000

/* UART :: LSR :: FE [03:03] */
#define BCHP_UART_LSR_FE_MASK                                      0x00000008
#define BCHP_UART_LSR_FE_SHIFT                                     3
#define BCHP_UART_LSR_FE_DEFAULT                                   0x00000000

/* UART :: LSR :: PE [02:02] */
#define BCHP_UART_LSR_PE_MASK                                      0x00000004
#define BCHP_UART_LSR_PE_SHIFT                                     2
#define BCHP_UART_LSR_PE_DEFAULT                                   0x00000000

/* UART :: LSR :: OE [01:01] */
#define BCHP_UART_LSR_OE_MASK                                      0x00000002
#define BCHP_UART_LSR_OE_SHIFT                                     1
#define BCHP_UART_LSR_OE_DEFAULT                                   0x00000000

/* UART :: LSR :: DR [00:00] */
#define BCHP_UART_LSR_DR_MASK                                      0x00000001
#define BCHP_UART_LSR_DR_SHIFT                                     0
#define BCHP_UART_LSR_DR_DEFAULT                                   0x00000000

/***************************************************************************
 *MSR - Modem Status Register
 ***************************************************************************/
/* UART :: MSR :: reserved0 [31:08] */
#define BCHP_UART_MSR_reserved0_MASK                               0xffffff00
#define BCHP_UART_MSR_reserved0_SHIFT                              8

/* UART :: MSR :: DCD [07:07] */
#define BCHP_UART_MSR_DCD_MASK                                     0x00000080
#define BCHP_UART_MSR_DCD_SHIFT                                    7
#define BCHP_UART_MSR_DCD_DEFAULT                                  0x00000000

/* UART :: MSR :: RI [06:06] */
#define BCHP_UART_MSR_RI_MASK                                      0x00000040
#define BCHP_UART_MSR_RI_SHIFT                                     6
#define BCHP_UART_MSR_RI_DEFAULT                                   0x00000000

/* UART :: MSR :: DSR [05:05] */
#define BCHP_UART_MSR_DSR_MASK                                     0x00000020
#define BCHP_UART_MSR_DSR_SHIFT                                    5
#define BCHP_UART_MSR_DSR_DEFAULT                                  0x00000000

/* UART :: MSR :: CTS [04:04] */
#define BCHP_UART_MSR_CTS_MASK                                     0x00000010
#define BCHP_UART_MSR_CTS_SHIFT                                    4
#define BCHP_UART_MSR_CTS_DEFAULT                                  0x00000000

/* UART :: MSR :: DDCD [03:03] */
#define BCHP_UART_MSR_DDCD_MASK                                    0x00000008
#define BCHP_UART_MSR_DDCD_SHIFT                                   3
#define BCHP_UART_MSR_DDCD_DEFAULT                                 0x00000000

/* UART :: MSR :: TERI [02:02] */
#define BCHP_UART_MSR_TERI_MASK                                    0x00000004
#define BCHP_UART_MSR_TERI_SHIFT                                   2
#define BCHP_UART_MSR_TERI_DEFAULT                                 0x00000000

/* UART :: MSR :: DDSR [01:01] */
#define BCHP_UART_MSR_DDSR_MASK                                    0x00000002
#define BCHP_UART_MSR_DDSR_SHIFT                                   1
#define BCHP_UART_MSR_DDSR_DEFAULT                                 0x00000000

/* UART :: MSR :: DCTS [00:00] */
#define BCHP_UART_MSR_DCTS_MASK                                    0x00000001
#define BCHP_UART_MSR_DCTS_SHIFT                                   0
#define BCHP_UART_MSR_DCTS_DEFAULT                                 0x00000000

/***************************************************************************
 *SCR - Scratchpad Register
 ***************************************************************************/
/* UART :: SCR :: reserved0 [31:08] */
#define BCHP_UART_SCR_reserved0_MASK                               0xffffff00
#define BCHP_UART_SCR_reserved0_SHIFT                              8

/* UART :: SCR :: SCR [07:00] */
#define BCHP_UART_SCR_SCR_MASK                                     0x000000ff
#define BCHP_UART_SCR_SCR_SHIFT                                    0
#define BCHP_UART_SCR_SCR_DEFAULT                                  0x00000000

#endif /* #ifndef BCHP_UART_H__ */

/* End of File */
