
# Copyright (C) 2006 Junjiro Okajima
# Copyright (C) 2006 Tomas Matejicek, slax.org
#
# LICENSE follows the described one in lzma.txt.

# $Id: Makefile,v 1.2 2014/11/19 09:12:54 wtchen Exp $

obj-m += unlzma.o sqlzma.o
unlzma-y := module.o
sqlzma-y := uncomp.o
