/***************************************************************************
 *     Copyright (c) 1999-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Tue Sep  3 03:07:41 2013
 *                 MD5 Checksum         d41d8cd98f00b204e9800998ecf8427e
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_H__
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_H__

/***************************************************************************
 *CPU_COMM_QUEUE_0_DATA_CPUC
 ***************************************************************************/
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD0    0x038f0800 /* Queue Word 0 Register */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD1    0x038f0804 /* Queue Word 1 Register */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD2    0x038f0808 /* Queue Word 2 Register */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD3    0x038f080c /* Queue Word 3 Register */

/***************************************************************************
 *WORD0 - Queue Word 0 Register
 ***************************************************************************/
/* CPU_COMM_QUEUE_0_DATA_CPUC :: WORD0 :: Q_DATA [31:00] */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD0_Q_DATA_MASK          0xffffffff
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD0_Q_DATA_SHIFT         0
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD0_Q_DATA_DEFAULT       0x00000000

/***************************************************************************
 *WORD1 - Queue Word 1 Register
 ***************************************************************************/
/* CPU_COMM_QUEUE_0_DATA_CPUC :: WORD1 :: Q_DATA [31:00] */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD1_Q_DATA_MASK          0xffffffff
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD1_Q_DATA_SHIFT         0
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD1_Q_DATA_DEFAULT       0x00000000

/***************************************************************************
 *WORD2 - Queue Word 2 Register
 ***************************************************************************/
/* CPU_COMM_QUEUE_0_DATA_CPUC :: WORD2 :: Q_DATA [31:00] */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD2_Q_DATA_MASK          0xffffffff
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD2_Q_DATA_SHIFT         0
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD2_Q_DATA_DEFAULT       0x00000000

/***************************************************************************
 *WORD3 - Queue Word 3 Register
 ***************************************************************************/
/* CPU_COMM_QUEUE_0_DATA_CPUC :: WORD3 :: Q_DATA [31:00] */
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD3_Q_DATA_MASK          0xffffffff
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD3_Q_DATA_SHIFT         0
#define BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_WORD3_Q_DATA_DEFAULT       0x00000000

#endif /* #ifndef BCHP_CPU_COMM_QUEUE_0_DATA_CPUC_H__ */

/* End of File */
